# Generated by Django 3.2.6 on 2021-10-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
